### ISSUE TITLE
Can mqtt-client-React-Native support to connect broker.emqx.io with TCP port 1883

### ISSUE THREAD

**Issue by iot-lorawan** [emqx/MQTT-Client-Examples#124]
Hi,
     Can mqtt-client-React-Native support to connect broker.emqx.io with TCP port 1883,not the websocket 8083,
it seems only support websocket mqtt?
     Thanks,
     Best Regards.

**Comment by zibuyu1995** [comment]
In React Native, using MQTT over TCP (port 1883) can be challenging due to the limitations of the React Native environment, which doesn't natively support TCP sockets as it does in a standard Node.js or browser environment. Typically, React Native applications use WebSockets for network communication because React Native's networking capabilities are based on what's available in the browser environment.

For MQTT, this often means using a WebSocket-enabled broker and connecting via the WebSocket protocol (typically on ports like 8083 or 8000 for non-SSL, and 8084 or 443 for SSL/TLS).

**Comment by iot-lorawan** [comment]
Hi zibuyu1995,
    Thanks for your response.Now I understand this limitation.

Best Regards.
